# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K9XaTybgL7mGRa92JtlUIvx4bzZ9IMqR
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load data
df = pd.read_excel("Dataset.xlsx")

# Clean missing/null records
df = df.dropna(subset=['Sales', 'Profit', 'Category', 'Sub-Category'])

# Calculate profit margins
profit_margins = df.groupby(['Category', 'Sub-Category']).agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum')
).reset_index()
profit_margins['Profit_Margin_%'] = (profit_margins['Total_Profit'] / profit_margins['Total_Sales']) * 100

print(profit_margins)

# Correlation between Inventory Days and Profitability
if 'Days_In_Inventory' in df.columns:
    correlation = df[['Days_In_Inventory', 'Profit']].corr()
    print("\nCorrelation between Inventory Days and Profitability:\n", correlation)

    # Visualize correlation
    sns.scatterplot(x='Days_In_Inventory', y='Profit', data=df)
    plt.title('Inventory Days vs Profit')
    plt.savefig('inventory_vs_profit.png')
    plt.show()
else:
    print("Column 'Days_In_Inventory' not found in data.")